//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Кант_Вино.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string Port {
            get {
                return ((string)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string BaudRate {
            get {
                return ((string)(this["BaudRate"]));
            }
            set {
                this["BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int PollingInterval {
            get {
                return ((int)(this["PollingInterval"]));
            }
            set {
                this["PollingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfDouble xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>0</double>
</ArrayOfDouble>")]
        public double[] CoefficientsPressure {
            get {
                return ((double[])(this["CoefficientsPressure"]));
            }
            set {
                this["CoefficientsPressure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfDouble xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
  <double>1</double>
</ArrayOfDouble>")]
        public double[] CoefficientsLevel {
            get {
                return ((double[])(this["CoefficientsLevel"]));
            }
            set {
                this["CoefficientsLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
</ArrayOfBoolean>")]
        public bool[] ItemsEnale {
            get {
                return ((bool[])(this["ItemsEnale"]));
            }
            set {
                this["ItemsEnale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfSingleGraphConfig xmlns:xsi=\"htt" +
            "p://www.w3.org/2001/XMLSchema-instance\"\r\n                        xmlns:xsd=\"http" +
            "://www.w3.org/2001/XMLSchema\">\r\n                        <SingleGraphConfig>\r\n   " +
            "                         <ymin>0</ymin>\r\n                            <ymax>1</ym" +
            "ax>\r\n                            <isYAuto>true</isYAuto>\r\n                      " +
            "      <curveName>Температура 1 (°C)</curveName>\r\n                            <cu" +
            "rveColor>-16776961</curveColor>\r\n                        </SingleGraphConfig>\r\n " +
            "                       <SingleGraphConfig>\r\n                            <ymin>0<" +
            "/ymin>\r\n                            <ymax>1</ymax>\r\n                            " +
            "<isYAuto>true</isYAuto>\r\n                            <curveName>Температура 2 (°" +
            "C)</curveName>\r\n                            <curveColor>-65536</curveColor>\r\n   " +
            "                     </SingleGraphConfig>\r\n                        <SingleGraphC" +
            "onfig>\r\n                            <ymin>0</ymin>\r\n                            " +
            "<ymax>1</ymax>\r\n                            <isYAuto>true</isYAuto>\r\n           " +
            "                 <curveName>Давление (атм)</curveName>\r\n                        " +
            "    <curveColor>-16776961</curveColor>\r\n                        </SingleGraphCon" +
            "fig>\r\n                        <SingleGraphConfig>\r\n                            <" +
            "ymin>0</ymin>\r\n                            <ymax>1</ymax>\r\n                     " +
            "       <isYAuto>true</isYAuto>\r\n                            <curveName>Уровень (" +
            "м)</curveName>\r\n                            <curveColor>-16776961</curveColor>\r\n" +
            "                        </SingleGraphConfig>\r\n                    </ArrayOfSingl" +
            "eGraphConfig>")]
        public SingleGraphConfig[] ItemsGConfig {
            get {
                return ((SingleGraphConfig[])(this["ItemsGConfig"]));
            }
            set {
                this["ItemsGConfig"] = value;
            }
        }
    }
}
